// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjyeuWR4J84er-11a5bQv4RGTlOiyaxm4',
    appId: '1:600926093973:web:38d7df72419b3bb080519c',
    messagingSenderId: '600926093973',
    projectId: 'inventory-abaa5',
    authDomain: 'inventory-abaa5.firebaseapp.com',
    storageBucket: 'inventory-abaa5.firebasestorage.app',
    measurementId: 'G-0VRL02EQR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeyzJpAAAgPq1BVc92D_T5OeQ1oZhSqgU',
    appId: '1:600926093973:android:698960d374f616c880519c',
    messagingSenderId: '600926093973',
    projectId: 'inventory-abaa5',
    storageBucket: 'inventory-abaa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoIe8SZZZDK1DsIeyjzLHLh2ubuwv4-0Q',
    appId: '1:600926093973:ios:36f52985df15056180519c',
    messagingSenderId: '600926093973',
    projectId: 'inventory-abaa5',
    storageBucket: 'inventory-abaa5.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoIe8SZZZDK1DsIeyjzLHLh2ubuwv4-0Q',
    appId: '1:600926093973:ios:36f52985df15056180519c',
    messagingSenderId: '600926093973',
    projectId: 'inventory-abaa5',
    storageBucket: 'inventory-abaa5.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjyeuWR4J84er-11a5bQv4RGTlOiyaxm4',
    appId: '1:600926093973:web:3932267c8c58fe6780519c',
    messagingSenderId: '600926093973',
    projectId: 'inventory-abaa5',
    authDomain: 'inventory-abaa5.firebaseapp.com',
    storageBucket: 'inventory-abaa5.firebasestorage.app',
    measurementId: 'G-MWNBJEPHE7',
  );

}